version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/frontend/src
    tty: true

  mysql_srv:
    image: mysql:8.0
    container_name: mysql_ctr
    stdin_open: true
    restart: always
    environment:
      MYSQL_DATABASE: k-link
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - ./backend/data:/var/lib/mysql
      - ./backend/conf:/etc/mysql/conf.d
      - ./backend/logs:/logs

  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: mysql_srv
    ports:
      - 8080:80

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      - mysql_srv
    env_file:
      - ./backend/.env
    ports:
      - 8001:8001
    volumes:
      - ./backend:/backend

volumes:
  mysql_srv:
    driver: local
